package squigly

type CssKey = "-webkit-line-clamp" |
  "::after (:after)" |
  "::backdrop" |
  "::before (:before)" |
  "::cue-region" |
  "::cue" |
  "::first-letter (:first-letter)" |
  "::first-line (:first-line)" |
  "::grammar-error" |
  "::marker" |
  "::part" |
  "::placeholder" |
  "::selection" |
  "::slotted" |
  "::spelling-error" |
  "::target-text" |
  ":active" |
  ":any-link" |
  ":blank" |
  ":checked" |
  ":current" |
  ":default" |
  ":defined" |
  ":dir" |
  ":disabled" |
  ":empty" |
  ":enabled" |
  ":first-child" |
  ":first-of-type" |
  ":first" |
  ":focus-visible" |
  ":focus-within" |
  ":focus" |
  ":fullscreen" |
  ":future" |
  ":has" |
  ":host-context()" |
  ":host()" |
  ":hover" |
  ":in-range" |
  ":indeterminate" |
  ":invalid" |
  ":is" |
  ":lang" |
  ":last-child" |
  ":last-of-type" |
  ":left" |
  ":link" |
  ":local-link" |
  ":not" |
  ":nth-child" |
  ":nth-col" |
  ":nth-last-child" |
  ":nth-last-col" |
  ":nth-last-of-type" |
  ":nth-of-type" |
  ":only-child" |
  ":only-of-type" |
  ":optional" |
  ":out-of-range" |
  ":past" |
  ":paused" |
  ":picture-in-picture" |
  ":placeholder-shown" |
  ":playing" |
  ":read-only" |
  ":read-write" |
  ":required" |
  ":right" |
  ":root" |
  ":scope" |
  ":target-within" |
  ":target" |
  ":user-invalid" |
  ":user-valid" |
  ":valid" |
  ":visited" |
  ":where" |
  "" |
  "@annotation" |
  "@bottom-center" |
  "@character-variant" |
  "@charset" |
  "@counter-style" |
  "@font-face" |
  "@font-feature-values" |
  "@historical-forms" |
  "@import" |
  "@keyframes" |
  "@left-bottom" |
  "@media" |
  "@namespace" |
  "@ornaments" |
  "@page" |
  "@property" |
  "@right-bottom" |
  "@styleset" |
  "@stylistic" |
  "@supports" |
  "@swash" |
  "@top-center" |
  "@viewport" |
  "<an-plus-b>" |
  "<angle-percentage>" |
  "<angle>" |
  "<basic-shape>" |
  "<blend-mode>" |
  "<color>" |
  "<counter>" |
  "<custom-ident>" |
  "<dimension>" |
  "<display-box>" |
  "<display-inside>" |
  "<display-internal>" |
  "<display-legacy>" |
  "<display-listitem>" |
  "<display-outside>" |
  "<filter-function>" |
  "<flex>" |
  "<frequency-percentage>" |
  "<frequency>" |
  "<gradient>" |
  "<ident>" |
  "<image>" |
  "<integer>" |
  "<length-percentage>" |
  "<length>" |
  "<number>" |
  "<percentage>" |
  "<position>" |
  "<ratio>" |
  "<resolution>" |
  "<shape>" |
  "<string>" |
  "<time-percentage>" |
  "<time>" |
  "<timing-function>" |
  "<transform-function>" |
  "<url>" |
  "A" |
  "accent-color" |
  "additive-symbols (@counter-style)" |
  "align-content" |
  "align-items" |
  "align-self" |
  "align-tracks" |
  "all" |
  "angle#deg" |
  "angle#grad" |
  "angle#rad" |
  "angle#turn" |
  "animation-delay" |
  "animation-direction" |
  "animation-duration" |
  "animation-fill-mode" |
  "animation-iteration-count" |
  "animation-name" |
  "animation-play-state" |
  "animation-timing-function" |
  "animation" |
  "annotation()" |
  "appearance" |
  "ascent-override (@font-face)" |
  "aspect-ratio" |
  "attr()" |
  "B" |
  "backdrop-filter" |
  "backface-visibility" |
  "background-attachment" |
  "background-blend-mode" |
  "background-clip" |
  "background-color" |
  "background-image" |
  "background-origin" |
  "background-position-x" |
  "background-position-y" |
  "background-position" |
  "background-repeat" |
  "background-size" |
  "background" |
  "bleed (@page)" |
  "block-overflow" |
  "block-size" |
  "blur()" |
  "border-block-color" |
  "border-block-end-color" |
  "border-block-end-style" |
  "border-block-end-width" |
  "border-block-end" |
  "border-block-start-color" |
  "border-block-start-style" |
  "border-block-start-width" |
  "border-block-start" |
  "border-block-style" |
  "border-block-width" |
  "border-block" |
  "border-bottom-color" |
  "border-bottom-left-radius" |
  "border-bottom-right-radius" |
  "border-bottom-style" |
  "border-bottom-width" |
  "border-bottom" |
  "border-collapse" |
  "border-color" |
  "border-end-end-radius" |
  "border-end-start-radius" |
  "border-image-outset" |
  "border-image-repeat" |
  "border-image-slice" |
  "border-image-source" |
  "border-image-width" |
  "border-image" |
  "border-inline-color" |
  "border-inline-end-color" |
  "border-inline-end-style" |
  "border-inline-end-width" |
  "border-inline-end" |
  "border-inline-start-color" |
  "border-inline-start-style" |
  "border-inline-start-width" |
  "border-inline-start" |
  "border-inline-style" |
  "border-inline-width" |
  "border-inline" |
  "border-left-color" |
  "border-left-style" |
  "border-left-width" |
  "border-left" |
  "border-radius" |
  "border-right-color" |
  "border-right-style" |
  "border-right-width" |
  "border-right" |
  "border-spacing" |
  "border-start-end-radius" |
  "border-start-start-radius" |
  "border-style" |
  "border-top-color" |
  "border-top-left-radius" |
  "border-top-right-radius" |
  "border-top-style" |
  "border-top-width" |
  "border-top" |
  "border-width" |
  "border" |
  "bottom" |
  "box-decoration-break" |
  "box-shadow" |
  "box-sizing" |
  "break-after" |
  "break-before" |
  "break-inside" |
  "brightness()" |
  "C" |
  "calc()" |
  "caption-side" |
  "caret-color" |
  "character-variant()" |
  "circle()" |
  "clamp()" |
  "clear" |
  "clip-path" |
  "clip" |
  "color-adjust" |
  "color-scheme" |
  "color" |
  "column-count" |
  "column-fill" |
  "column-gap" |
  "column-rule-color" |
  "column-rule-style" |
  "column-rule-width" |
  "column-rule" |
  "column-span" |
  "column-width" |
  "columns" |
  "conic-gradient()" |
  "contain" |
  "content-visibility" |
  "content" |
  "contrast()" |
  "counter-increment" |
  "counter-reset" |
  "counter-set" |
  "counters()" |
  "cross-fade()" |
  "cubic-bezier()" |
  "cursor" |
  "D" |
  "descent-override (@font-face)" |
  "direction" |
  "display" |
  "drop-shadow()" |
  "E" |
  "element()" |
  "ellipse()" |
  "empty-cells" |
  "env()" |
  "F" |
  "fallback (@counter-style)" |
  "filter" |
  "fit-content()" |
  "flex_value#fr" |
  "flex-basis" |
  "flex-direction" |
  "flex-flow" |
  "flex-grow" |
  "flex-shrink" |
  "flex-wrap" |
  "flex" |
  "float" |
  "font-display (@font-face)" |
  "font-family (@font-face)" |
  "font-family" |
  "font-feature-settings (@font-face)" |
  "font-feature-settings" |
  "font-kerning" |
  "font-language-override" |
  "font-optical-sizing" |
  "font-size-adjust" |
  "font-size" |
  "font-stretch (@font-face)" |
  "font-stretch" |
  "font-style (@font-face)" |
  "font-style" |
  "font-synthesis" |
  "font-variant (@font-face)" |
  "font-variant-alternates" |
  "font-variant-caps" |
  "font-variant-east-asian" |
  "font-variant-ligatures" |
  "font-variant-numeric" |
  "font-variant-position" |
  "font-variant" |
  "font-variation-settings (@font-face)" |
  "font-variation-settings" |
  "font-weight (@font-face)" |
  "font-weight" |
  "font" |
  "forced-color-adjust" |
  "format()" |
  "frequency#Hz" |
  "frequency#kHz" |
  "G" |
  "gap" |
  "grayscale()" |
  "grid-area" |
  "grid-auto-columns" |
  "grid-auto-flow" |
  "grid-auto-rows" |
  "grid-column-end" |
  "grid-column-start" |
  "grid-column" |
  "grid-row-end" |
  "grid-row-start" |
  "grid-row" |
  "grid-template-areas" |
  "grid-template-columns" |
  "grid-template-rows" |
  "grid-template" |
  "grid" |
  "H" |
  "hanging-punctuation" |
  "height (@viewport)" |
  "height" |
  "hsl()" |
  "hsla()" |
  "hue-rotate()" |
  "hyphens" |
  "I" |
  "image-orientation" |
  "image-rendering" |
  "image-resolution" |
  "image-set()" |
  "image()" |
  "inherit" |
  "inherits (@property)" |
  "initial-letter-align" |
  "initial-letter" |
  "initial-value (@property)" |
  "initial" |
  "inline-size" |
  "inset-block-end" |
  "inset-block-start" |
  "inset-block" |
  "inset-inline-end" |
  "inset-inline-start" |
  "inset-inline" |
  "inset" |
  "inset()" |
  "invert()" |
  "isolation" |
  "J" |
  "justify-content" |
  "justify-items" |
  "justify-self" |
  "justify-tracks" |
  "K" |
  "L" |
  "leader()" |
  "left" |
  "length#ch" |
  "length#cm" |
  "length#em" |
  "length#ex" |
  "length#in" |
  "length#mm" |
  "length#pc" |
  "length#pt" |
  "length#px" |
  "length#Q" |
  "length#rem" |
  "length#vh" |
  "length#vmax" |
  "length#vmin" |
  "length#vw" |
  "letter-spacing" |
  "line-break" |
  "line-clamp" |
  "line-gap-override (@font-face)" |
  "line-height-step" |
  "line-height" |
  "linear-gradient()" |
  "list-style-image" |
  "list-style-position" |
  "list-style-type" |
  "list-style" |
  "local()" |
  "M" |
  "margin-block-end" |
  "margin-block-start" |
  "margin-block" |
  "margin-bottom" |
  "margin-inline-end" |
  "margin-inline-start" |
  "margin-inline" |
  "margin-left" |
  "margin-right" |
  "margin-top" |
  "margin-trim" |
  "margin" |
  "marks (@page)" |
  "mask-border-mode" |
  "mask-border-outset" |
  "mask-border-repeat" |
  "mask-border-slice" |
  "mask-border-source" |
  "mask-border-width" |
  "mask-border" |
  "mask-clip" |
  "mask-composite" |
  "mask-image" |
  "mask-mode" |
  "mask-origin" |
  "mask-position" |
  "mask-repeat" |
  "mask-size" |
  "mask-type" |
  "mask" |
  "masonry-auto-flow" |
  "math-style" |
  "matrix()" |
  "matrix3d()" |
  "max-block-size" |
  "max-height (@viewport)" |
  "max-height" |
  "max-inline-size" |
  "max-lines" |
  "max-width (@viewport)" |
  "max-width" |
  "max-zoom (@viewport)" |
  "max()" |
  "min-block-size" |
  "min-height (@viewport)" |
  "min-height" |
  "min-inline-size" |
  "min-width (@viewport)" |
  "min-width" |
  "min-zoom (@viewport)" |
  "min()" |
  "minmax()" |
  "mix-blend-mode" |
  "N" |
  "negative (@counter-style)" |
  "O" |
  "object-fit" |
  "object-position" |
  "offset-anchor" |
  "offset-distance" |
  "offset-path" |
  "offset-position" |
  "offset-rotate" |
  "offset" |
  "opacity" |
  "opacity()" |
  "order" |
  "orientation (@viewport)" |
  "ornaments()" |
  "orphans" |
  "Others" |
  "outline-color" |
  "outline-offset" |
  "outline-style" |
  "outline-width" |
  "outline" |
  "overflow-anchor" |
  "overflow-block" |
  "overflow-clip-margin" |
  "overflow-inline" |
  "overflow-wrap" |
  "overflow-x" |
  "overflow-y" |
  "overflow" |
  "overscroll-behavior-block" |
  "overscroll-behavior-inline" |
  "overscroll-behavior-x" |
  "overscroll-behavior-y" |
  "overscroll-behavior" |
  "P" |
  "pad (@counter-style)" |
  "padding-block-end" |
  "padding-block-start" |
  "padding-block" |
  "padding-bottom" |
  "padding-inline-end" |
  "padding-inline-start" |
  "padding-inline" |
  "padding-left" |
  "padding-right" |
  "padding-top" |
  "padding" |
  "page-break-after" |
  "page-break-before" |
  "page-break-inside" |
  "paint-order" |
  "paint()" |
  "path()" |
  "perspective-origin" |
  "perspective" |
  "perspective()" |
  "place-content" |
  "place-items" |
  "place-self" |
  "pointer-events" |
  "polygon()" |
  "position" |
  "prefix (@counter-style)" |
  "Pseudo-classes" |
  "Pseudo-elements" |
  "Q" |
  "quotes" |
  "R" |
  "radial-gradient()" |
  "range (@counter-style)" |
  "rect()" |
  "repeat()" |
  "repeating-linear-gradient()" |
  "repeating-radial-gradient()" |
  "resize" |
  "resolution#dpcm" |
  "resolution#dpi" |
  "resolution#dppx" |
  "resolution#x" |
  "revert" |
  "rgb()" |
  "rgba()" |
  "right" |
  "rotate" |
  "rotate()" |
  "rotate3d()" |
  "rotateX()" |
  "rotateY()" |
  "rotateZ()" |
  "row-gap" |
  "ruby-align" |
  "ruby-merge" |
  "ruby-position" |
  "S" |
  "saturate()" |
  "scale" |
  "scale()" |
  "scale3d()" |
  "scaleX()" |
  "scaleY()" |
  "scaleZ()" |
  "scroll-behavior" |
  "scroll-margin-block-end" |
  "scroll-margin-block-start" |
  "scroll-margin-block" |
  "scroll-margin-bottom" |
  "scroll-margin-inline-end" |
  "scroll-margin-inline-start" |
  "scroll-margin-inline" |
  "scroll-margin-left" |
  "scroll-margin-right" |
  "scroll-margin-top" |
  "scroll-margin" |
  "scroll-padding-block-end" |
  "scroll-padding-block-start" |
  "scroll-padding-block" |
  "scroll-padding-bottom" |
  "scroll-padding-inline-end" |
  "scroll-padding-inline-start" |
  "scroll-padding-inline" |
  "scroll-padding-left" |
  "scroll-padding-right" |
  "scroll-padding-top" |
  "scroll-padding" |
  "scroll-snap-align" |
  "scroll-snap-stop" |
  "scroll-snap-type" |
  "scrollbar-color" |
  "scrollbar-gutter" |
  "scrollbar-width" |
  "selector()" |
  "sepia()" |
  "shape-image-threshold" |
  "shape-margin" |
  "shape-outside" |
  "size (@page)" |
  "size-adjust (@font-face)" |
  "skew()" |
  "skewX()" |
  "skewY()" |
  "speak-as (@counter-style)" |
  "src (@font-face)" |
  "steps()" |
  "styleset()" |
  "stylistic()" |
  "suffix (@counter-style)" |
  "swash()" |
  "symbols (@counter-style)" |
  "symbols()" |
  "syntax (@property)" |
  "system (@counter-style)" |
  "T" |
  "tab-size" |
  "table-layout" |
  "target-counter()" |
  "target-counters()" |
  "target-text()" |
  "text-align-last" |
  "text-align" |
  "text-combine-upright" |
  "text-decoration-color" |
  "text-decoration-line" |
  "text-decoration-skip-ink" |
  "text-decoration-skip" |
  "text-decoration-style" |
  "text-decoration-thickness" |
  "text-decoration" |
  "text-emphasis-color" |
  "text-emphasis-position" |
  "text-emphasis-style" |
  "text-emphasis" |
  "text-indent" |
  "text-justify" |
  "text-orientation" |
  "text-overflow" |
  "text-rendering" |
  "text-shadow" |
  "text-size-adjust" |
  "text-transform" |
  "text-underline-offset" |
  "text-underline-position" |
  "time#ms" |
  "time#s" |
  "top" |
  "touch-action" |
  "transform-box" |
  "transform-origin" |
  "transform-style" |
  "transform" |
  "transition-delay" |
  "transition-duration" |
  "transition-property" |
  "transition-timing-function" |
  "transition" |
  "translate" |
  "translate()" |
  "translate3d()" |
  "translateX()" |
  "translateY()" |
  "translateZ()" |
  "type css = --*" |
  "type()" |
  "U" |
  "unicode-bidi" |
  "unicode-range (@font-face)" |
  "unset" |
  "url()" |
  "user-select" |
  "user-zoom (@viewport)" |
  "V" |
  "var()" |
  "vertical-align" |
  "viewport-fit (@viewport)" |
  "visibility" |
  "W" |
  "white-space" |
  "widows" |
  "width (@viewport)" |
  "width" |
  "will-change" |
  "word-break" |
  "word-spacing" |
  "word-wrap" |
  "writing-mode" |
  "X" |
  "z-index" |
  "Z" |
  "zoom (@viewport)"